// *APP INIT TYPES
// export const APP_INIT_TYPES = {
//   CNTRL_APP_INIT: 'CNTRL_APP_INIT'
// };

// // *AUTH TYPES
// export const AUTH_TYPES = {
//   CNTRL_LOG_IN: 'CNTRL_LOG_IN',
//   CNTRL_REFRESH_TOKEN: 'CNTRL_REFRESH_TOKEN',
//   RX_SET_AUTH_BOOL: 'RX_SET_AUTH_BOOL',
//   CNTRL_LOGOUT: 'CNTRL_LOGOUT',
// };

// *TOKEN todo delete  Token ==============
// export const TOKEN = {
//   // !GET TOKEN PERMISSION
//   CNTRL_GET_TOKEN_PERMISSION: 'CNTRL_GET_TOKEN_PERMISSION',
//   RX_GET_TOKEN_PERMISSION: 'RX_GET_TOKEN_PERMISSION',
//   RX_GET_TOKEN_PERMISSION_PENDING: 'RX_GET_TOKEN_PERMISSION_PENDING',
//   RX_GET_TOKEN_PERMISSION_DONE: 'RX_GET_TOKEN_PERMISSION_DONE'
//
// };
export const TEST = {
  CNTRL_GET_TEST: 'CNTRL_GET_TEST',
  RX_GET_TEST: 'RX_GET_TEST',
  RX_GET_TEST_PENDING: 'RX_GET_TEST_PENDING',
  RX_GET_TEST_DONE: 'RX_GET_TEST_DONE'
};
